
// LN 2021 

#ifndef CARLSIM_SPIKE_GENERATORS_API_H
#define CARLSIM_SPIKE_GENERATORS_API_H

#include <carlsim_conf_api.h>

#ifndef CARLSIM_SPIKE_GENERATORS_API
#  ifdef carlsim_spike_generators_EXPORTS
#    define CARLSIM_SPIKE_GENERATORS_API CARLSIM_EXPORT
#    define CARLSIM_SPIKE_GENERATORS_EXTERN CARLSIM_EXPORT_EXTERN
#  else
#    define CARLSIM_SPIKE_GENERATORS_API CARLSIM_IMPORT
#    define CARLSIM_SPIKE_GENERATORS_EXTERN CARLSIM_EXPORT_EXTERN
#  endif
#endif


#endif // CARLSIM_SPIKE_GENERATORS_API_H