
// LN 2021 

#ifndef CARLSIM_SIMPLE_WEIGHT_TUNER_API_H
#define CARLSIM_SIMPLE_WEIGHT_TUNER_API_H

#include <carlsim_conf_api.h>

#ifndef CARLSIM_SIMPLE_WEIGHT_TUNER_API
#  ifdef carlsim_simple_weight_tuner_EXPORTS
#    define CARLSIM_SIMPLE_WEIGHT_TUNER_API CARLSIM_EXPORT
#    define CARLSIM_SIMPLE_WEIGHT_TUNER_EXTERN CARLSIM_EXPORT_EXTERN
#  else
#    define CARLSIM_SIMPLE_WEIGHT_TUNER_API CARLSIM_IMPORT
#    define CARLSIM_SIMPLE_WEIGHT_TUNER_EXTERN CARLSIM_EXPORT_EXTERN
#  endif
#endif


#endif // CARLSIM_SIMPLE_WEIGHT_TUNER_API_H