
// LN 2021 

#ifndef CARLSIM_VISUAL_STIMULUS_API_H
#define CARLSIM_VISUAL_STIMULUS_API_H

#include <carlsim_conf_api.h>

#ifndef CARLSIM_VISUAL_STIMULUS_API
#  ifdef carlsim_visual_stimulus_EXPORTS
#    define CARLSIM_VISUAL_STIMULUS_API CARLSIM_EXPORT
#    define CARLSIM_VISUAL_STIMULUS_EXTERN CARLSIM_EXPORT_EXTERN
#  else
#    define CARLSIM_VISUAL_STIMULUS_API CARLSIM_IMPORT
#    define CARLSIM_VISUAL_STIMULUS_EXTERN CARLSIM_EXPORT_EXTERN
#  endif
#endif


#endif // CARLSIM_VISUAL_STIMULUS_API_H