
// LN 2021 

#ifndef CARLSIM_PERSISTANCE_API_H
#define CARLSIM_PERSISTANCE_API_H

#include <carlsim_conf_api.h>

#ifndef CARLSIM_PERSISTANCE_API
#  ifdef carlsim_persistance_EXPORTS
#    define CARLSIM_PERSISTANCE_API CARLSIM_EXPORT
#    define CARLSIM_PERSISTANCE_EXTERN CARLSIM_EXPORT_EXTERN
#  else
#    define CARLSIM_PERSISTANCE_API CARLSIM_IMPORT
#    define CARLSIM_PERSISTANCE_EXTERN CARLSIM_EXPORT_EXTERN
#  endif
#endif


#endif // CARLSIM_PERSISTANCE_API_H